server:
  port: 8085
spring:
  application:
    name: TurbineService
  security:
    user:
      name: user
      password: 123
eureka:
  client:
    service-url:
      defaultZone: http://user:123@192.168.88.129:8081/eureka/
turbine:
  aggregator:
    cluster-config: spring
  app-config: config-single-server, eureka-single-client
  combine-host-port: true
  cluster-name-expression: metadata['cluster']