server:
  port: 8083
#eureka:
#  client:
#    service-url:
eureka:
  instance:
    prefer-ip-address: false
    metadata-map:
      cluster: spring
management:
  endpoints:
    web:
      exposure:
        include: "*, hystrix.stream"