server:
  port: 8083
#eureka:
#  client:
#    service-url:
eureka:
  instance:
    prefer-ip-address: false
    metadata-map:
      cluster: spring
management:
  endpoints:
    web:
      exposure:
        include: "*, hystrix.stream"
turbine:
  aggregator:
    cluster-config: default
  app-config: config-single-server, eureka-single-client
  cluster-name-expression: new String("default")